In [155]:
import geocoder  # first step we should install geocoder liprary. pip install geocoder.
from geopy.geocoders import Nominatim
import pandas as pd  # read data from xlsx file.
from sqlalchemy import create_engine


import geopandas as gpd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [156]:
user = "postgres"
password = "Ww4756"
host = "localhost"
port = 5432
database = "casestudy"
conn = f"postgresql://{user}:{password}@{host}:{port}/{database}"
engine = create_engine(conn)

In [157]:
file_name = "bsvr_noktalari.xlsx"
data = pd.read_excel (r'../caseData/bsvr_noktalari.xlsx') 
df = pd.DataFrame(data)

df = df.rename(columns={'Kişi Adı': 'applicantName', 'Adresi': 'ad'})

In [158]:
df

,Başvuru Numarası,Kişi Adı,Adresi,Şehri
0,1,John Doe 1,"Güvenevler Mahallesi, mesnevi sokak, 28 numara",Ankara
1,2,John Doe 2,Dikmen caddesi 143,Ankara
2,3,John Doe 3,ragıp tüzün caddesi 3 numara,Ankara
3,4,John Doe 4,"Remzi Oğuz Arık Mahallesi, Tunalı Hilmi Caddes...",Ankara
4,5,John Doe 5,"Meşrutiyet Mahallesi, Konur Sokak, No 11/6, Ça...",Ankara

In [159]:


for index, row in df.iterrows():
    g = geocoder.arcgis(row['Adresi'] + row['Şehri'])
    keys = list(g.json.values())
    df.at[index, 'lat'] = keys[3]
    df.at[index, 'lng'] = keys[4]

In [160]:
df

,Başvuru Numarası,Kişi Adı,Adresi,Şehri,lat,lng
0,1,John Doe 1,"Güvenevler Mahallesi, mesnevi sokak, 28 numara",Ankara,39.89545,32.852186
1,2,John Doe 2,Dikmen caddesi 143,Ankara,39.89186,32.841570
2,3,John Doe 3,ragıp tüzün caddesi 3 numara,Ankara,39.96503,32.806900
3,4,John Doe 4,"Remzi Oğuz Arık Mahallesi, Tunalı Hilmi Caddes...",Ankara,39.90274,32.860210
4,5,John Doe 5,"Meşrutiyet Mahallesi, Konur Sokak, No 11/6, Ça...",Ankara,39.91882,32.856290

In [162]:
applicantGdf= gpd.GeoDataFrame(df, geometry= gpd.points_from_xy(df.lng, df.lat))
applicantGdf=applicantGdf.drop(columns=['lng','lat'])

applicantGdf

,Başvuru Numarası,Kişi Adı,Adresi,Şehri,geometry
0,1,John Doe 1,"Güvenevler Mahallesi, mesnevi sokak, 28 numara",Ankara,POINT (32.85219 39.89545)
1,2,John Doe 2,Dikmen caddesi 143,Ankara,POINT (32.84157 39.89186)
2,3,John Doe 3,ragıp tüzün caddesi 3 numara,Ankara,POINT (32.80690 39.96503)
3,4,John Doe 4,"Remzi Oğuz Arık Mahallesi, Tunalı Hilmi Caddes...",Ankara,POINT (32.86021 39.90274)
4,5,John Doe 5,"Meşrutiyet Mahallesi, Konur Sokak, No 11/6, Ça...",Ankara,POINT (32.85629 39.91882)

In [163]:
applicantGdf.geometry.crs = {'init':'epsg:4326'}

/Users/eyuptunahanunal/anaconda3/lib/python3.11/site-packages/pyproj/crs/crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

In [165]:
applicantGdf.to_postgis(name="applicants", con=engine, schema="public")